// Paths and public values only. Load secrets inside each child through SECRET_ENV_MAP.
const cwd = process.env.NFTECH_RELEASE_DIR;
if (!cwd || !cwd.startsWith("/")) throw new Error("Set an absolute NFTECH_RELEASE_DIR.");
const env = {
  NODE_ENV: "production",
  APP_MODE: "production",
  NEXT_PUBLIC_APP_MODE: "production",
  APP_ORIGIN: process.env.APP_ORIGIN,
  PRIVY_APP_ID: process.env.PRIVY_APP_ID,
  KMS_KEY_RESOURCE: process.env.KMS_KEY_RESOURCE,
  SECRET_ENV_MAP: process.env.SECRET_ENV_MAP,
  SUPPORT_EMAIL: process.env.SUPPORT_EMAIL,
  SELLER_NAME: process.env.SELLER_NAME,
  CHECKOUT_ENABLED: process.env.CHECKOUT_ENABLED ?? "false",
  PAYMENT_PROVIDER: process.env.PAYMENT_PROVIDER ?? "disabled",
  PAYMENT_RECIPIENT: process.env.PAYMENT_RECIPIENT,
  PAYMENT_CONFIRMATIONS: process.env.PAYMENT_CONFIRMATIONS ?? "12",
  PAYMENT_SOURCE_CONFIRMATIONS: process.env.PAYMENT_SOURCE_CONFIRMATIONS ?? "12",
  TOKENFLIGHT_INTEGRATOR_ID: process.env.TOKENFLIGHT_INTEGRATOR_ID,
  ENS_ENABLED: process.env.ENS_ENABLED ?? "false",
  ENS_WRITE_ENABLED: process.env.ENS_WRITE_ENABLED ?? "false",
  ENS_CHAIN_ID: process.env.ENS_CHAIN_ID ?? "1",
  ENS_SIMULATED: "false",
  NFT_EMBEDDED_DB: "false",
  ENS_PARENT_NAME: process.env.ENS_PARENT_NAME,
  ENS_PARENT_REGISTRY: process.env.ENS_PARENT_REGISTRY,
  ENS_CITY_REGISTRY_TOKYO: process.env.ENS_CITY_REGISTRY_TOKYO,
  ENS_APP_RESOLVER: process.env.ENS_APP_RESOLVER,
  WORLD_APP_ID: process.env.WORLD_APP_ID,
  WORLD_RP_ID: process.env.WORLD_RP_ID,
  WORLD_ENVIRONMENT: process.env.WORLD_ENVIRONMENT ?? "production",
  WORLD_ALLOW_STAGING: process.env.WORLD_ALLOW_STAGING ?? "false",
  WORLD_ACTION_TRIP: process.env.WORLD_ACTION_TRIP ?? "trip-activate",
  WORLD_APPROVALS: process.env.WORLD_APPROVALS ?? "session",
  WORLD_AGENTS_ISSUER: process.env.WORLD_AGENTS_ISSUER ?? "https://sandbox.auth.world.org",
  WORLD_AGENTS_CLIENT_ID: process.env.WORLD_AGENTS_CLIENT_ID,
  WORLD_AGENTS_REDIRECT_URI: process.env.WORLD_AGENTS_REDIRECT_URI,
  SPLIT_NETWORK: process.env.SPLIT_NETWORK ?? "base",
  TRUST_PROXY: "false",
};
module.exports = {
  apps: [
    {
      name: "nftech-app",
      cwd,
      script: "node_modules/next/dist/bin/next",
      args: "start --hostname 127.0.0.1 --port 3100",
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "768M",
      kill_timeout: 10000,
      env,
    },
    {
      name: "nftech-worker",
      cwd,
      script: "src/worker/index.ts",
      interpreter: "node",
      node_args: "--import tsx",
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "384M",
      kill_timeout: 15000,
      env,
    },
  ],
};
